name: high_low
description: A project for cycle of articles about isolator and other packages of me
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  json_annotation: ^4.3.0
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  flutter_lints: ^1.0.4
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true