name: high_low
description: A project for cycle of articles about isolator and other packages of me
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  json_annotation: ^4.6.0
  logger: ^1.1.0
  intl: ^0.18.0
  isolator:
    path: ../
  dio: ^4.0.6
  provider: ^6.0.3
  retrofit: ^3.0.0+1
  anitex: ^3.0.1
  device_preview: ^1.1.0
  google_fonts: ^3.0.1
  # Generated packages
  yalo_locale:
    path: ./.yalo_locale
  yalo_assets:
    path: ./.yalo_assets

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3
#  yalo: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/